#!/usr/bin/env python3
"""Runs inside the build container. Copies the shared archinstall config
template from bootstrap/ into the ISO build profile, so both install flows
stay driven by one file.

The credentials that pair with this config are NOT produced here - they're
generated by iso/build-iso.ps1 from a password typed at build time, hashed
in the container, and written straight into the profile. Nothing about the
password lives in this repo.

This used to also patch `-e force_password_expiry=true` into the first-boot
service's ansible-playbook invocation, because the ISO shipped a hash of a
publicly-known placeholder password that had to be force-changed at first
login. With a real build-time password there's nothing to force-change, and
the expiry approach had a nasty edge anyway: the machine boots straight into
SDDM, whose expired-password handling is version-dependent, so a forced
expiry risked a graphical login you couldn't get past.
"""
import json

SRC = "/repo/bootstrap/user_configuration.template.json"
DEST = "/tmp/profile/airootfs/root/archproject-bootstrap/user_configuration.json"

with open(SRC) as f:
    config = json.load(f)

with open(DEST, "w") as f:
    json.dump(config, f, indent=2)

print(f"Wrote {DEST}")
